import {InMemoryDbService} from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const users = [
      {id: 0, name: 'Pena Gibson'},
      {id: 1, name: 'Geneva Henderson'},
      {id: 2, name: 'Graciela Burt'},
      {id: 3, name: 'Schultz Hancock'},
      {id: 4, name: 'Fletcher Terrell'},
      {id: 5, name: 'Tessa Wallace'},
      {id: 6, name: 'Kristie Stokes'},
      {id: 7, name: 'Lewis Wong'},
      {id: 8, name: 'Annmarie Salas'},
      {id: 9, name: 'Gamble Lambert'},
      {id: 10, name: 'Vazquez English'},
      {id: 11, name: 'Welch Ramirez'},
      {id: 12, name: 'Myrtle Kirkland'},
      {id: 13, name: 'Mosley Wiley'},
      {id: 14, name: 'Cooke Ray'},
      {id: 15, name: 'Corina Conley'},
      {id: 16, name: 'Gladys Monroe'},
      {id: 17, name: 'Keith Wise'},
      {id: 18, name: 'Marcy Ayala'},
      {id: 19, name: 'Duncan Alexander'},
      {id: 20, name: 'Carroll Caldwell'},
      {id: 21, name: 'Susanne Perry'},
      {id: 22, name: 'Ruby Welch'},
      {id: 23, name: 'Garrison Boyle'},
      {id: 24, name: 'Robbie Tillman'},
      {id: 25, name: 'Fowler Roth'},
      {id: 26, name: 'Clayton Kinney'},
      {id: 27, name: 'York Johnson'},
      {id: 28, name: 'Daugherty Cooper'},
      {id: 29, name: 'Kendra Stone'},
      {id: 30, name: 'Cohen Rocha'},
      {id: 31, name: 'Tara Norris'},
      {id: 32, name: 'Harper Carr'},
      {id: 33, name: 'Mcknight King'},
      {id: 34, name: 'Berry Mcmahon'},
      {id: 35, name: 'Ruth Pitts'},
      {id: 36, name: 'Houston Phillips'},
      {id: 37, name: 'Crosby Summers'},
      {id: 38, name: 'Woods Travis'},
      {id: 39, name: 'Ebony Chase'},
      {id: 40, name: 'Randi Estes'},
      {id: 41, name: 'Genevieve Reeves'},
      {id: 42, name: 'Christy Estrada'},
      {id: 43, name: 'Wilma Oconnor'},
      {id: 44, name: 'Pauline Walker'},
      {id: 45, name: 'Julianne Calderon'},
      {id: 46, name: 'Nola Gregory'},
      {id: 47, name: 'Macdonald Sawyer'},
      {id: 48, name: 'Latonya Cain'},
      {id: 49, name: 'Catherine Dotson'}
    ];
    return {users};
  }
}
